name: Selenium Docker CI/CD

on:
  push:
    branches:
      - main

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Containers
        run: docker compose build

      - name: Start Containers
        run: docker compose up -d

      - name: Wait for Grid
        run: sleep 30

      - name: Execute Tests
        run: docker compose exec -T selenium-tests-firefox mvn test

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selenium-reports
          path: reports/firefox

      - name: Stop Containers
        if: always()
 run: docker compose down
