name: Selenium Firefox CI

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Containers
        run: docker compose build

      - name: Start Services
        run: docker compose up -d app firefox

      - name: Wait for services
        run: sleep 15

      - name: Run Firefox Tests
        run: docker compose run --rm selenium-tests-firefox

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selenium-reports
          path: reports/

      - name: Cleanup
        if: always()
        run: docker compose down -v
