name: Selenium Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Docker Image
        run: docker compose build

      - name: Run Tests (${{ matrix.browser }})
        run: |
          docker compose run \
            -e BROWSER=${{ matrix.browser }} \
            selenium-tests

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports-${{ matrix.browser }}
          path: reports/${{ matrix.browser }}/

      - name: Cleanup
        if: always()
        run: docker compose down -v
